---
- name: Ensure Python pip is installed
  apt:
    name: python3-pip
    state: present
  become: true
  tags: addons

- name: Install Kubernetes Python library
  pip:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - kubernetes
  tags: addons

- name: Create cattle-system namespace if it doesn't exist
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
  loop:
    - clusterops
  when: NODE_ROLE == "master" and INDEX == 1
  tags: addons, namespace

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.chart }}"
  loop:
    - {name: "rancher-stable", chart: "https://releases.rancher.com/server-charts/stable"}
    - {name: "jetstack", chart: "https://charts.jetstack.io"}
    - {name: "longhorn", chart: "https://charts.longhorn.io"}
    - {name: "prometheus-community", chart: "https://prometheus-community.github.io/helm-charts"}
    - {name: "kedacore", chart: "https://kedacore.github.io/charts"}
    - {name: "argo", chart: "https://argoproj.github.io/argo-helm"}
  tags: addons, helmrepo
  when: NODE_ROLE == "master" and INDEX == 1

- name: Download cert-manager crd manifest to the cluster.
  ansible.builtin.get_url:
    url: "https://github.com/cert-manager/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.crds.yaml"
    dest: /opt/rancher/rke2/manifest/cert-manager.crds.yaml
    mode: '0664'
  when: NODE_ROLE == "master" and INDEX == 1 and ( enable_cert_manager or enable_rancher )
  tags: addons, cert-manager, rancher

- name: Apply cert-manager crd manifest to the cluster.
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: /opt/rancher/rke2/manifest/cert-manager.crds.yaml
    namespace: cert-manager
  when: NODE_ROLE == "master" and INDEX == 1 and ( enable_cert_manager or enable_rancher )
  tags: addons, cert-manager, rancher

- name: RKE2 Ingress Nginx Config
  template:
    src: addons/rke2-ingress-nginx/config.yml.j2
    dest: /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
  when: (rke2_ingress_nginx_config is defined and rke2_ingress_nginx_config | length > 0) and (NODE_ROLE == "master" and INDEX == 1)
  tags: addons, rke2-ingress-nginx

- include: "./addons/cert-manager.yml"
  when: enable_cert_manager

- include: "./addons/rancher.yml"
  when: enable_rancher

- include: "./addons/longhorn.yml"
  when: enable_longhorn

- include: "./addons/prometheus.yml"
  when: enable_prometheus

- include: "./addons/keda.yml"
  when: enable_keda

- include: "./addons/argocd.yml"
  when: enable_argocd
