- name: Copy config file to worker nodes
  template:
    src: configs/worker/config.yml
    dest: /etc/rancher/rke2/config.yaml
  notify: Retart RKE2 agent service
  tags: rke2, config, worker

- name: Install RKE2 Agent
  shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION={{ RKE2_VERSION }} INSTALL_RKE2_TYPE="agent" sh -
  args:
    executable: /bin/bash
    creates: /var/lib/rancher/rke2/bin/
  tags: rke2, config, worker

- name: Enable RKE2 agent service
  ansible.builtin.service:
    name: rke2-agent
    enabled: yes

- name: Start RKE2 agent service
  ansible.builtin.service:
    name: rke2-agent
    state: started
